# Generated by Django 5.0.7 on 2024-07-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmaterial",
            name="quantity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="remainder",
            field=models.FloatField(),
        ),
    ]
