# Generated by Django 5.0.7 on 2024-07-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_productmaterial_quantity_alter_warehouse_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmaterial",
            name="quantity",
            field=models.FloatField(default=0),
        ),
    ]
