# Generated by Django 5.0.7 on 2024-07-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_productmaterial_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmaterial",
            old_name="material_id",
            new_name="material",
        ),
        migrations.RenameField(
            model_name="productmaterial",
            old_name="product_id",
            new_name="product",
        ),
        migrations.AlterField(
            model_name="productmaterial",
            name="quantity",
            field=models.FloatField(),
        ),
    ]
