# Generated by Django 5.0.7 on 2024-07-23 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_material_id_productmaterial_material_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="warehouse",
            old_name="material_id",
            new_name="material",
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productmaterial",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_materials",
                to="api.product",
            ),
        ),
    ]
