# Generated by Django 5.0.7 on 2024-07-26 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_material_id_warehouse_material_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
    ]
